service: service-B

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    apiGateway: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
